### ISSUE TITLE
Add support for Rails v7.2

### ISSUE THREAD

**Issue by ezekg** [MaxLap/activerecord_where_assoc#14]
The Rails team has a [`7-2-stable`](https://github.com/rails/rails/tree/7-2-stable) branch ready, which should be released soon.

Currently using [a small monkey patch](https://github.com/keygen-sh/keygen-api/blob/b38eb80511a788559e0a851d0a198f4d10f480e6/config/initializers/active_record_where_assoc.rb), which seems to work. I'll make a PR.

**Comment by MaxLap** [comment]
I released 1.1.5 with the change.

Thanks!
