### ISSUE TITLE
Missing documentation for poly_belongs_to

### ISSUE THREAD

**Issue by fschwahn** [MaxLap/activerecord_where_assoc#5]
When you use `where_assoc_exists` with a polymorphic association without specifying `poly_belongs_to`, the error message leads me to https://github.com/MaxLap/activerecord_where_assoc#poly_belongs_to - however this part of the README does not exist, and it's actually quite hard to find information about this option. There's excellent documentation here:
https://github.com/MaxLap/activerecord_where_assoc/blob/8230ea7967eaca420bf0045c03c8890c0e27e7cd/lib/active_record_where_assoc/query_methods.rb#L179-L198

But it's hard to find using githubs UI. It would probably be enough to add the section and link to this part of the code.

**Comment by MaxLap** [comment]
Good catch! Thanks for reporting the issue.

I forgot about such urls in the error messages when I cleanup the README. I moved everything to the code's documentation. I will fix this ASAP.

You can also view that documentation here: https://maxlap.github.io/activerecord_where_assoc/ActiveRecordWhereAssoc/QueryMethods.html#module-ActiveRecordWhereAssoc::QueryMethods-label-3Apoly_belongs_to+option

**Comment by MaxLap** [comment]
I pushed version 1.0.1 which fixes this issue. I found another broken link in an error message, and the readme had 2 links that got broken when i moved things to documentation, all solved.

Thanks for the heads up!
