### ISSUE TITLE
NoMethodError - undefined method 'join_keys' for ActiveRecord::Reflection::HasManyReflection

### ISSUE THREAD

**Issue by cristi** [MaxLap/activerecord_where_assoc#7]
hey MaxLap, thanks for this gem, it looks like exactly what I'm looking for.

However, I seem to be missing something. I've added the gem to the gemfile and bundled.
But trying even the simplest method `Post.where_assoc_exists(:comments)` raises the `undefined method 'join_keys'`
I'm on rails 6.1.0, ruby 2.7.1p83, activerecord_where_assoc 1.1.1, postgres 11

The gemfile is rather standard for a rails app, from the used gems, I think only kaminari and ransack are touching ActiveRecord

I'm sure it's something stupid I'm missing, maybe you can point me in the right direction.

Thanks, Cristi

**Comment by MaxLap** [comment]
Sorry, I forgot to make a release with the fix that was already committed for rails 6.1.0.

I just did so, please update the gem to 1.1.2, it should solve your problem. If not, do not hesitate to reopen this issue (with a full backtrace please).

**Comment by cristi** [comment]
@MaxLap thanks for the quick fix. I can confirm it works. And after playing with the queries for 10 minutes it already solved my problem, something that would have probably taken me hours and hours to solve in a less efficient way.

**Comment by MaxLap** [comment]
Very glad the gem helped you! Thanks for taking to time to report the issue you encountered.

**Comment by ranska** [comment]
thanks a lot I just update to rails 6.1 and I just update this gem and it works ! 
Thank you for your job :)
